jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-def:
        BUILD: stack
        GHCVER: 8.2.2
        STACK_YAML: stack.yaml
      lts-12:
        BUILD: stack
        GHCVER: 8.4.3
        STACK_YAML: stack-lts-12.yaml
      nightly:
        BUILD: stack
        GHCVER: 8.6.1
        STACK_YAML: stack-nightly.yaml

    maxParallel: 3
  steps:
  - script: |
      case "$BUILD" in
        style)
          export PATH="$TRAVIS_BUILD_DIR"/hlint:$PATH
          ;;
        cabal)
          export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/happy/1.19.5/bin:/opt/alex/3.1.7/bin:/opt/cabal/$CABALVER/bin:$PATH
          ;;
        *)
          export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:/opt/happy/1.19.5/bin:/opt/alex/3.1.7/bin:$PATH
          ;;
      esac
      ./.travis-setup.sh
    displayName: 'Setup Path'
  - script: |
      if ! [ "$BUILD" = style ]; then echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"; fi
         set -ex
      case "$BUILD" in
        style)
          ./etc/scripts/get-hlint.sh
          ;;
        cabal)
          cabal --version
          cabal update
          rm -f $HOME/.cabal/bin/stack
          echo "stack is located at $(which stack)"
          stack --version

          echo Removing any old dist files
          rm -f $(stack --stack-yaml=$STACK_YAML path --dist-dir)/stack-*.tar.gz

          echo To avoid custom Cabal setup business, switching temporarily to Simple
          cp stack.cabal stack.orig-cabal
          sed 's@build-type\:.*@build-type\: Simple@' < stack.orig-cabal > stack.cabal

          echo Generating new dist with pvp bounds in the cabal file
          stack --system-ghc --stack-yaml=$STACK_YAML sdist --pvp-bounds=both

          echo Grabbing the newly generated stack.cabal file from the tarball
          tar xf $(stack --system-ghc --compiler=ghc-$GHCVER path --dist-dir)/stack-*.tar.gz --wildcards --strip-components=1 '*/stack.cabal'

          echo Switching back to Custom build type
          cp stack.cabal stack.orig-cabal
          sed 's@build-type\:.*@build-type\: Custom@' < stack.orig-cabal > stack.cabal
          rm -f stack.orig-cabal

          echo Performing the actual build now that we have the right stack.cabal
          cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1
          ;;
        *)
          stack --no-terminal build Cabal
          stack --no-terminal test --only-dependencies
          ;;
      esac
      set +ex
    displayName: 'Installation'
