jobs:
- template: azure-pipeline-template.yml
  parameters:
    name: macOS
    vmImage: macOS-10.13
    os: mac

- template: azure-pipeline-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    os: linux

- template: azure-windows-template.yml
  parameters:
   name: Windows
   vmImage: vs2017-win2016
